language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t yanggwi/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=ture yanggwi/react-test-app npm test

after_success:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  
  - docker build -t yanggwi/docker-frontend ./frontend
  - docker build -t yanggwi/docker-backend ./backend
  - docker build -t yanggwi/docker-nginx ./nginx

  - docker push yanggwi/docker-frontend
  - docker push yanggwi/docker-backend
  - docker push yanggwi/docker-nginx

deploy:
  provide: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-151918530964
  bucket_path: "docker-test"
  on:
    branch: master

access_key_id: $AWS_ACCESS_ID
secret_access_key: $AWS_SECRET_KEY
